### PR TITLE
Fixed issue #165. Wrong version number.

### PR DESCRIPTION
**Pull request by neverrend**
image

Will now display the current version and commit as per #165

### CODE REVIEW

**Comment by oxr463** [comment]
@neverrend, can you rebase on master?

I'm looking at your branch, and it looks like your commits start after 49dc17c9b3e8dfadff7acdb37250de7cded2ff63.

**Comment by neverrend** [comment]
Yeah give me a sec to get it all loaded on this new comp.

**Comment by oxr463** [comment]
@neverrend did you see this?

> Will output the tag of the latest tagged commit across all branches --https://stackoverflow.com/questions/1404796/how-to-get-the-latest-tag-name-in-current-branch-in-git

```
git describe --tags $(git rev-list --tags --max-count=1)
```

**Comment by neverrend** [comment]
Oh that's handy. I need to see if it works as intended and then rebase on master.

**Comment by oxr463** [comment]
ping @neverrend

**Pull request merged**
