### PR TITLE
Properly filter the renameat2 syscall introduced in Linux v3.15.

### PR DESCRIPTION
**Pull request by KimonHoffmann**
Handle the renameat2 syscall analogous to renameat, as their only
difference is an additional flags attribute, which isn't relevant to
the path based adjustments performed by proot.

### CODE REVIEW

**Comment by KimonHoffmann** [comment]
Fixes #147.

**Comment by KimonHoffmann** [comment]
This first version had a syntax error in the compatibility extension. I will open a new PR with the fixed version.

**Comment by josch** [comment]
Instead of opening a new pull request, you can also just update your existing pull request.

https://stackoverflow.com/questions/9790448/how-to-update-a-pull-request-from-forked-repo
https://stackoverflow.com/questions/7947322/preferred-github-workflow-for-updating-a-pull-request-after-code-review

**Comment by KimonHoffmann** [comment]
Thanks for the links to the relevant discussions, next time I'll just update the PR at hand.

IIRC a few years back i tried updating a PR with rewritten history and it didn't work, but that might have been due to some other thing I did wrong back then.

**Pull request closed without merging**
