### PR TITLE
WIP: Translate unix socket paths in sendto and recvfrom syscalls

### PR DESCRIPTION
**Pull request by pespin**
For recvfrom, I tried following the example of PR_accept, but I'm
lacking an extra register to put the max_size, so another approach needs
to be found.

Test: make check-test-ssssssss.c

### CODE REVIEW

**Comment by oxr463** [comment]
> For recvfrom, I tried following the example of PR_accept, but I'm
> lacking an extra register to put the max_size, so another approach needs
> to be found.
> 
> Test: make check-test-ssssssss.c

So what is the state of this PR? Is your implementation still incomplete?

**Comment by pespin** [comment]
> So what is the state of this PR? Is your implementation still incomplete?

I haven't worked on it and I expect someone else with better knowledge on proot code base to take care of it, since I don't know what's the expected approach regarding this extra parameter needed. Still, it's good to have this PR open to showcase the missing feature and have somebody take over it.

**Comment by oxr463** [comment]
@pespin, thanks for the update. I will add this to the big list of things to do. Just wanted to try to get all the stale PR's merged.

**Comment by pespin** [comment]
@oxr463 was the related feature properly implemented already? Or you just closed the PR due to being unfinished for a long time?

**Comment by oxr463** [comment]
> @oxr463 was the related feature properly implemented already? Or you just closed the PR due to being unfinished for a long time?

The latter. Trying to clean things up a bit.

**Pull request closed without merging**
