### PR TITLE
Remove some of the FHS assumptions with tests

### PR DESCRIPTION
**Pull request by civodul**
While packaging PRoot for GNU Guix, I found that tests make a few FHS assumptions that do not hold in our build environments.  The first patch here fixes most of them; the second one fixes a syntax issue with Bash.

There's a couple of places that assume the existence of /usr and /usr/share.  In Guix we patch them by looking for /gnu, which is known to always exist: https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/patches/proot-test-fhs.patch#n39 .  I'm not sure how to fix them in a way that is not Guix-specific.  Thoughts?

Thanks.

### CODE REVIEW

**Comment by vincenthage** [comment]
Hi!

Thanks for the fix.
Can you update this PR (either with a small commit or by closing/opening it) so that the Travis CI can run the tests and check that it's alright?

For the Guix-specific fix, would it work to add local fake symlink or an additional proot binding to redirect /usr towards /gnu if /usr does not exit?

**Comment by civodul** [comment]
Hello,

vincenthage <notifications@github.com> skribis:

> Can you update this PR (either with a small commit or by closing/opening it) so that the Travis CI can run the tests and check that it's alright?

I’d rather not add gratuitous commits but it seems I can’t close it
either.  Am I missing something?

> For the Guix-specific fix, would it work to add local fake symlink or an additional proot binding to redirect /usr towards /gnu if /usr does not exit?

Actually I just had an idea:

For `test-5bed7141.c` /etc would work everywhere I think.

For `test-5467b986.sh` though, maybe `/dev` and then checking for
`/dev/pts`?

WDYT?

Ludo’.

**Comment by jopasserat** [comment]
@civodul: don't worry for the gratuitous commits we can always squash them before merging the branch

**Comment by vincenthage** [comment]
All [tests](https://travis-ci.org/proot-me/PRoot/builds/272982213?utm_source=github_status&utm_medium=notification) passed, PR is ready to merge.

**Comment by civodul** [comment]
Awesome, thank you.  (And apologies for not being more responsive!)

**Comment by jopasserat** [comment]
@civodul can you please do one last change before we can merge?
That is replace the backquotes with `$(...)` in the shell scripts.

This follows guidelines from [shellcheck](https://github.com/koalaman/shellcheck/wiki/SC2006)

Also, do you want to fix the two tests you were mentioning before we merge?
  - [ ] test-5bed7141.c
  - [ ] test-5467b986.sh

**Comment by oxr463** [comment]
> Also, do you want to fix the two tests you were mentioning before we merge?
> 
>     * [ ]  test-5bed7141.c

@jopasserat , not entirely sure what needs to be done for this?

**Comment by jopasserat** [comment]
Not entirely sure @oxr463 , I guess it was referring to the paths used in the test file.
Especially, this path: 
https://github.com/proot-me/PRoot/blob/master/tests/test-5bed7141.c#L39
might be specific to some systems (not an assertion, more of an hypothesis)?

**Comment by oxr463** [comment]
```c
--- source/tests/test-5bed7141.c 2017-05-11 15:34:23.088472743 +0200 +++ source/tests/test-5bed7141.c 2017-05-11 15:34:27.052450235 +0200 @@ -80,7 +80,7 @@ int main(int argc, char *argv[]) exit(EXIT_FAILURE); case 0: /* child */ - status = chdir("/usr"); + status = chdir("/gnu"); if (status < 0) { perror("chdir"); exit(EXIT_FAILURE); 
```
Source: https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/patches/proot-test-fhs.patch#n39

**Pull request closed without merging**
