### PR TITLE
Fix use of size

### PR DESCRIPTION
**Pull request by jopasserat**
I think it's important enough to be merged in master without waiting for a new release bringing features from next.

What do you think @alkino ?

I'll make a static RC build with this fix available as a release in [proot-static-build](https://github.com/proot-me/proot-static-build)

### CODE REVIEW

**Comment by alkino** [comment]
Maybe we can do a 5.1.1 with this one and the other one for seccomp.

**Comment by jopasserat** [comment]
Yep this one is definitely worth a 5.1.1
(I'm finalising the Docker to build the static binaries at the moment)

As for seccomp we don't really have a proper fix yet.
Typically it stills crashes for CARE when re-executed with seccomp (due to the change of user id and kernel version).

Do you think we should release a non-Seccomp version?
I'm fine with it, but I don't know what to expect from a performance point of view.

**Comment by alkino** [comment]
As previously said, I don't know seccomp at all. So...

**Comment by 62f** [comment]
Which version of Ubuntu? What is the output of  dmesg? Keep in mind the ‘hotfix’ will keep modern kernels from running, and proot binary has only been compiled for x86_64.

**Comment by Flytreels** [comment]
This problem is fixed in the new version,sorry!

**Pull request merged**
